version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "mysecretpassword"
